name: Publish to PyPI using Trusted Publisher

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Micromamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: build-env
          create-args: >-
            python=3.11
            pip
            setuptools
            wheel
            -c conda-forge
            -c bioconda
            hic-straw
            numpy
            pandas
            cooler
            h5py

      - name: Install `build` via pip
        shell: bash -l {0}
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build the package
        shell: bash -l {0}
        run: |
          python -m build

      - name: Publish to PyPI using Trusted Publisher
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://upload.pypi.org/legacy/
